-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
SELECT 
c.name,
COUNT(fc.film_id) AS num_films
FROM category AS c 
LEFT JOIN film_category AS fc
ON c.category_id = fc.category_id
GROUP BY name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT
    s.store_id,
    c.city,
    cc.country
FROM store AS s
LEFT JOIN address AS a
    ON s.address_id = a.address_id
LEFT JOIN city AS c
    ON a.city_id = c.city_id
LEFT JOIN country AS cc
    ON c.country_id = cc.country_id;


-- 3. Calculate the total revenue generated by each store in dollars.
-- store>inventory>rental>payment
SELECT
    s.store_id,
    SUM(p.amount) AS revenue
FROM store AS s
LEFT JOIN inventory AS i
	ON s.store_id = i.store_id
LEFT JOIN rental AS r
	ON i.inventory_id = r.inventory_id
LEFT JOIN payment AS p
	ON r.rental_id = p.rental_id
GROUP BY s.store_id;
    
-- 4. Determine the average running time of films for each category.
-- LEFT category > film_category > film

SELECT
	c.name,
    AVG(f.length) AS avg_length
FROM category AS c
LEFT JOIN film_category AS fc
	ON c.category_id = fc.category_id
LEFT JOIN film as f
	ON fc.film_id = f.film_id
GROUP BY c.name;

-- Identify the film categories with the longest average running time.
SELECT
    c.name,
    ROUND(AVG(f.length),2) AS avg_length
FROM category AS c
LEFT JOIN film_category AS fc
    ON c.category_id = fc.category_id
LEFT JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY avg_length DESC
LIMIT 1;


-- Display the top 10 most frequently rented movies in descending order.
-- LEFT film > inventory > rental
SELECT
    f.title,
    COUNT(r.rental_id) AS num_rentals
FROM film AS f
LEFT JOIN inventory AS i
    ON f.film_id = i.film_id
LEFT JOIN rental AS r
    ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY num_rentals DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT
    f.title,
    i.inventory_id,
    i.store_id,
    CASE 
        WHEN i.inventory_id IS NOT NULL THEN 'Yes - Available'
        ELSE 'No - Not Available'
    END AS availability
FROM film AS f
LEFT JOIN inventory AS i
    ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
    AND i.store_id = 1;


-- Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

SELECT DISTINCT
    f.title,
    CASE 
        WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability_status
FROM film AS f
LEFT JOIN inventory AS i
    ON f.film_id = i.film_id
ORDER BY f.title;
